//Get Reqquest
GET http://localhost:5000/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2NjZmZmQ4OTM5ZTQwMzA0MWYwODciLCJpYXQiOjE2NDM1MzgxOTEsImV4cCI6MTY3NTA5NTc5MX0.iJPlx2bkKRJiBloAhnhNdriIcWEbp4JOEVNbFl9w_gI



###

POST http://localhost:5000/users/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2NjZmZmQ4OTM5ZTQwMzA0MWYwODciLCJpYXQiOjE2NDM1MzgxOTEsImV4cCI6MTY3NTA5NTc5MX0.iJPlx2bkKRJiBloAhnhNdriIcWEbp4JOEVNbFl9w_gI

{
    "title": "Joy shree raam part2",
    "body": "khela hobei mne hotei hbe"
}


###
PUT http://localhost:5000/users/notes/61f66762d8939e403041f08e 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2NjZmZmQ4OTM5ZTQwMzA0MWYwODciLCJpYXQiOjE2NDM1MzgxOTEsImV4cCI6MTY3NTA5NTc5MX0.iJPlx2bkKRJiBloAhnhNdriIcWEbp4JOEVNbFl9w_gI

{
    "title": "Joy shree ram",
    "body": "erom korle khelbona"
}

###

DELETE  http://localhost:5000/users/notes/61f66794d8939e403041f094 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY2NjZmZmQ4OTM5ZTQwMzA0MWYwODciLCJpYXQiOjE2NDM1MzgxOTEsImV4cCI6MTY3NTA5NTc5MX0.iJPlx2bkKRJiBloAhnhNdriIcWEbp4JOEVNbFl9w_gI




